### PR TITLE
#162304307 deploy apps to heroku

### PR DESCRIPTION
**Pull request by KvNGCzA**
#### What does this PR do?
Enable deployment of review, staging and production apps on heroku

#### Description of Task to be completed?
- configure webpack for production mode

#### How should this be manually tested?
- push a branch
- create a pull request

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#162304307](https://www.pivotaltracker.com/story/show/162304307)

#### Screenshots (if appropriate)
screen shot 2018-12-04 at 8 30 59 pm

#### Questions:
N/A

#### Link to review App
- [Review App](https://valinor-ah-frontend-stag-pr-14.herokuapp.com/)

### CODE REVIEW

**Comment by mbilesanmi** [comment]
Clicking on the site title reloads the page, Why?

**Comment by KvNGCzA** [comment]
> Clicking on the site title reloads the page, Why?

@mbilesanmi This is just a placeholder. That is where the logo will be. So that is the behavior the logo will have.

**Review by tersoo-atsen — APPROVED** [review]
LGTM

**Comment by mbilesanmi** [comment]
> > Clicking on the site title reloads the page, Why?
> 
> @mbilesanmi This is just a placeholder. That is where the logo will be. So that is the behavior the logo will have.

This should have the same behaviour as clicking the home button.

**Review by sulenchy — APPROVED** [review]
LGTM

**Pull request merged**
